* emacs-data
This is a repository that contains data about various versions of Emacs.
At present, it contains lists of built-in libraries of recent releases and the Git version.
This will be used for another Nix project of mine, which is related to building Emacs configuration with Nix.
Thus the data is provided via a Nix flake API.

While [[https://github.com/purcell/package-lint/][package-lint]] contains similar data for linting packages, this project serves a different purpose, so there are significant differences between them:

- It collects data about unstable versions (from [[https://github.com/nix-community/emacs-overlay][emacs-overlay]]) as well.
- It does not run Emacs, but it checks out the source repository of Emacs and find all source files matching a particular pattern. The result is based on file names, and not on provided features.
- Rather than storing diffs between versions, it keeps a complete snapshot of data from each version. If you are interested, you can use your favourite diff program to compare changes.

Because it only collects data from static source trees, it runs very fast!
Also, it is easy to add support for new versions.
** Usage
The Nix flake API is available in =lib=.
